#!/usr/bin/env python3
"""Generate KISAO ontology data from OLS API.

This script fetches all KISAO terms from the EBI Ontology Lookup Service (OLS)
and generates a Python module containing term names and ancestor relationships.

Usage:
    poetry run python scripts/generate_kisao_data.py

The output is written to biosim_server/compatibility/kisao_data.py
"""

import asyncio
import sys
from pathlib import Path
from typing import Any
from urllib.parse import quote

import aiohttp
import yaml

# OLS4 API base URL
OLS_API_BASE = "https://www.ebi.ac.uk/ols4/api"


def load_equivalence_category_ids() -> set[str]:
    """Load equivalence category IDs from the curated YAML file."""
    yaml_path = (
        Path(__file__).parent.parent
        / "biosim_server"
        / "compatibility"
        / "equivalence_categories.yaml"
    )
    with open(yaml_path) as f:
        data = yaml.safe_load(f)
    return {entry["id"] for entry in data["categories"]}


async def fetch_all_terms(session: aiohttp.ClientSession) -> list[dict[str, Any]]:
    """Fetch all KISAO terms from OLS API with pagination."""
    terms: list[dict[str, Any]] = []
    page = 0
    page_size = 100

    print("Fetching KISAO terms from OLS API...")

    while True:
        url = f"{OLS_API_BASE}/ontologies/kisao/terms?page={page}&size={page_size}"
        async with session.get(url) as resp:
            if resp.status != 200:
                print(f"Error fetching page {page}: {resp.status}")
                break

            data = await resp.json()
            embedded = data.get("_embedded", {})
            page_terms = embedded.get("terms", [])

            if not page_terms:
                break

            terms.extend(page_terms)

            page_info = data.get("page", {})
            total_pages = page_info.get("totalPages", 1)
            print(f"  Page {page + 1}/{total_pages} - fetched {len(page_terms)} terms")

            if page >= total_pages - 1:
                break

            page += 1

    print(f"Total terms fetched: {len(terms)}")
    return terms


async def fetch_ancestors(session: aiohttp.ClientSession, term_iri: str) -> list[str]:
    """Fetch ancestor IDs for a term using its IRI."""
    # Double URL-encode the IRI for the OLS API
    encoded_iri = quote(quote(term_iri, safe=""), safe="")
    url = f"{OLS_API_BASE}/ontologies/kisao/terms/{encoded_iri}/ancestors?size=100"

    try:
        async with session.get(url, timeout=aiohttp.ClientTimeout(total=10)) as resp:
            if resp.status != 200:
                return []

            data = await resp.json()
            embedded = data.get("_embedded", {})
            ancestors = embedded.get("terms", [])

            return [a.get("obo_id", "") for a in ancestors if a.get("obo_id")]
    except Exception as e:
        print(f"  Warning: Failed to fetch ancestors for {term_iri}: {e}")
        return []


async def process_terms(terms: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    """Process terms and fetch their ancestors."""
    result: dict[str, dict[str, Any]] = {}

    print("\nFetching ancestor chains...")

    # Process in batches to avoid overwhelming the API
    batch_size = 20

    async with aiohttp.ClientSession() as session:
        for i in range(0, len(terms), batch_size):
            batch = terms[i:i + batch_size]
            tasks = []

            for term in batch:
                obo_id = term.get("obo_id", "")
                label = term.get("label", "")
                iri = term.get("iri", "")
                is_obsolete = term.get("is_obsolete", False)

                if not obo_id or is_obsolete:
                    continue

                tasks.append((obo_id, label, iri))

            # Fetch ancestors for this batch concurrently
            ancestor_tasks = [
                fetch_ancestors(session, iri)
                for _, _, iri in tasks
            ]
            ancestors_results = await asyncio.gather(*ancestor_tasks)

            for (obo_id, label, _), ancestors in zip(tasks, ancestors_results):
                result[obo_id] = {
                    "name": label,
                    "ancestors": ancestors,
                }

            print(f"  Processed {min(i + batch_size, len(terms))}/{len(terms)} terms")

    return result


def generate_python_module(terms_data: dict[str, dict[str, Any]], equivalence_category_ids: set[str]) -> str:
    """Generate Python module source code."""
    lines = [
        '"""KISAO ontology data - AUTO-GENERATED, DO NOT EDIT.',
        '',
        'This file is generated by scripts/generate_kisao_data.py',
        'To update, run: poetry run python scripts/generate_kisao_data.py',
        '"""',
        '',
        'from typing import TypedDict',
        '',
        '',
        'class KisaoTermData(TypedDict):',
        '    """Data for a single KISAO term."""',
        '    name: str',
        '    ancestors: list[str]',
        '',
        '',
        '# All KISAO terms with names and ancestor chains',
        'KISAO_TERMS: dict[str, KisaoTermData] = {',
    ]

    # Sort by KISAO ID for consistent output
    for kisao_id in sorted(terms_data.keys()):
        data = terms_data[kisao_id]
        name = data["name"].replace('"', '\\"')
        ancestors = data["ancestors"]
        ancestors_str = ", ".join(f'"{a}"' for a in sorted(ancestors))
        lines.append(f'    "{kisao_id}": {{"name": "{name}", "ancestors": [{ancestors_str}]}},')

    lines.append('}')
    lines.append('')
    lines.append('')
    lines.append('# Ancestor categories that define algorithm equivalence groups.')
    lines.append('# Two algorithms are considered equivalent if they share an ancestor in this set.')
    lines.append('# These categories represent meaningful groupings like "ODE solver", "stochastic method", etc.')
    lines.append('EQUIVALENCE_CATEGORIES: set[str] = {')

    # Add equivalence categories, but only those that exist in the fetched terms
    existing_categories = set()
    for kisao_id, data in terms_data.items():
        if kisao_id in equivalence_category_ids:
            existing_categories.add(kisao_id)
        for ancestor in data["ancestors"]:
            if ancestor in equivalence_category_ids:
                existing_categories.add(ancestor)

    for cat_id in sorted(existing_categories):
        cat_name = terms_data.get(cat_id, {}).get("name", "unknown")
        lines.append(f'    "{cat_id}",  # {cat_name}')

    lines.append('}')
    lines.append('')

    return '\n'.join(lines)


async def main() -> int:
    """Main entry point."""
    # Determine output path
    script_dir = Path(__file__).parent
    project_root = script_dir.parent
    output_path = project_root / "biosim_server" / "compatibility" / "kisao_data.py"

    async with aiohttp.ClientSession() as session:
        # Fetch all terms
        terms = await fetch_all_terms(session)

        if not terms:
            print("Error: No terms fetched")
            return 1

    # Process terms and fetch ancestors
    terms_data = await process_terms(terms)

    if not terms_data:
        print("Error: No terms processed")
        return 1

    # Load equivalence categories from curated YAML
    equivalence_category_ids = load_equivalence_category_ids()
    print(f"\nLoaded {len(equivalence_category_ids)} equivalence categories from YAML")

    # Generate and write the Python module
    module_content = generate_python_module(terms_data, equivalence_category_ids)
    output_path.write_text(module_content)

    print(f"\nGenerated {output_path}")
    print(f"  Total terms: {len(terms_data)}")

    return 0


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
